"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2024 TikTok Pte. Ltd.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ClientSimpleSendRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_ID_FIELD_NUMBER: builtins.int
    RECEIVER_ID_FIELD_NUMBER: builtins.int
    PAYLOAD_FIELD_NUMBER: builtins.int
    message_id: builtins.str
    receiver_id: builtins.str
    payload: builtins.bytes
    def __init__(
        self,
        *,
        message_id: builtins.str = ...,
        receiver_id: builtins.str = ...,
        payload: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message_id", b"message_id", "payload", b"payload", "receiver_id", b"receiver_id"]) -> None: ...

global___ClientSimpleSendRequest = ClientSimpleSendRequest

@typing.final
class ClientSimpleRecvRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_ID_FIELD_NUMBER: builtins.int
    message_id: builtins.str
    def __init__(
        self,
        *,
        message_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message_id", b"message_id"]) -> None: ...

global___ClientSimpleRecvRequest = ClientSimpleRecvRequest

@typing.final
class ServerSimpleSendRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_ID_FIELD_NUMBER: builtins.int
    PAYLOAD_FIELD_NUMBER: builtins.int
    message_id: builtins.str
    payload: builtins.bytes
    def __init__(
        self,
        *,
        message_id: builtins.str = ...,
        payload: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message_id", b"message_id", "payload", b"payload"]) -> None: ...

global___ServerSimpleSendRequest = ServerSimpleSendRequest

@typing.final
class Response(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    PAYLOAD_FIELD_NUMBER: builtins.int
    ERROR_CODE_FIELD_NUMBER: builtins.int
    ERROR_MSG_FIELD_NUMBER: builtins.int
    success: builtins.bool
    payload: builtins.bytes
    error_code: builtins.int
    error_msg: builtins.str
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        payload: builtins.bytes | None = ...,
        error_code: builtins.int | None = ...,
        error_msg: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_error_code", b"_error_code", "_error_msg", b"_error_msg", "_payload", b"_payload", "error_code", b"error_code", "error_msg", b"error_msg", "payload", b"payload"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_error_code", b"_error_code", "_error_msg", b"_error_msg", "_payload", b"_payload", "error_code", b"error_code", "error_msg", b"error_msg", "payload", b"payload", "success", b"success"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_error_code", b"_error_code"]) -> typing.Literal["error_code"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_error_msg", b"_error_msg"]) -> typing.Literal["error_msg"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_payload", b"_payload"]) -> typing.Literal["payload"] | None: ...

global___Response = Response
