# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simple.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csimple.proto\x12\x10petnet.simple.v1\"S\n\x17\x43lientSimpleSendRequest\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12\x13\n\x0breceiver_id\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\"-\n\x17\x43lientSimpleRecvRequest\x12\x12\n\nmessage_id\x18\x01 \x01(\t\">\n\x17ServerSimpleSendRequest\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\"\x8b\x01\n\x08Response\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x14\n\x07payload\x18\x02 \x01(\x0cH\x00\x88\x01\x01\x12\x17\n\nerror_code\x18\x03 \x01(\x05H\x01\x88\x01\x01\x12\x16\n\terror_msg\x18\x04 \x01(\tH\x02\x88\x01\x01\x42\n\n\x08_payloadB\r\n\x0b_error_codeB\x0c\n\n_error_msg2\xa6\x02\n\x13SimpleRequestServer\x12Y\n\x10\x43lientSimpleSend\x12).petnet.simple.v1.ClientSimpleSendRequest\x1a\x1a.petnet.simple.v1.Response\x12Y\n\x10\x43lientSimpleRecv\x12).petnet.simple.v1.ClientSimpleRecvRequest\x1a\x1a.petnet.simple.v1.Response\x12Y\n\x10ServerSimpleSend\x12).petnet.simple.v1.ServerSimpleSendRequest\x1a\x1a.petnet.simple.v1.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'simple_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CLIENTSIMPLESENDREQUEST']._serialized_start=34
  _globals['_CLIENTSIMPLESENDREQUEST']._serialized_end=117
  _globals['_CLIENTSIMPLERECVREQUEST']._serialized_start=119
  _globals['_CLIENTSIMPLERECVREQUEST']._serialized_end=164
  _globals['_SERVERSIMPLESENDREQUEST']._serialized_start=166
  _globals['_SERVERSIMPLESENDREQUEST']._serialized_end=228
  _globals['_RESPONSE']._serialized_start=231
  _globals['_RESPONSE']._serialized_end=370
  _globals['_SIMPLEREQUESTSERVER']._serialized_start=373
  _globals['_SIMPLEREQUESTSERVER']._serialized_end=667
# @@protoc_insertion_point(module_scope)
